# Generated by Django 4.0.8 on 2022-10-16 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=75)),
                ('state', models.CharField(blank=True, max_length=25)),
                ('zipcode', models.CharField(blank=True, max_length=200)),
                ('avatar_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='owner_id',
        ),
        migrations.DeleteModel(
            name='ScheduleUser',
        ),
        migrations.AddField(
            model_name='participant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_calendar.profile'),
        ),
    ]
