# Generated by Django 4.0.8 on 2022-10-25 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule_calendar', '0008_alter_addressbook_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='owner',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
