# Generated by Django 4.0.8 on 2022-10-28 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule_calendar', '0013_remove_addressbook_contacts_addressbook_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_book',
        ),
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AddressBook',
        ),
    ]
