# Generated by Django 4.0.8 on 2022-10-29 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule_calendar', '0015_remove_profile_contacts_addressbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbook',
            name='owner',
        ),
        migrations.AddField(
            model_name='addressbook',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
