# Generated by Django 4.0.8 on 2022-10-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_calendar', '0016_remove_addressbook_owner_addressbook_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='event',
        ),
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ManyToManyField(blank=True, to='schedule_calendar.event'),
        ),
    ]
