# Generated by Django 4.0.8 on 2022-10-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_calendar', '0017_remove_participant_event_participant_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='participant',
            new_name='participants',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='participants',
        ),
        migrations.AddField(
            model_name='participant',
            name='participants',
            field=models.ManyToManyField(to='schedule_calendar.profile', blank=True),
        ),
    ]
