# Generated by Django 4.0.8 on 2022-10-31 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule_calendar', '0019_alter_participant_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
